version: '3'
services:
  db:
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=dev
    volumes:
      - database_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432

  redis:
    image: redis:3
    ports:
     - "6379:6379"


volumes:
  database_data: {}
